### ISSUE TITLE
Automation Testing for 6 Scenarios [Gayatri]

### ISSUE THREAD

**Issue by Gayatrivl** [externship-sag/RSATeam1#109]
**Complete the automation for the following 6 scenarios based on the criteria below.
Criteria**
 

- [x] Create a new project
- [x]  Use page object model
- [x]  Create feature files for each scenario
- [ ]  After completing all 6 scenarios, try parallel execution
- [ ]  Create your own repository
- [ ]  Push your code on a daily basis
- [ ]  Execute your automation from Jenkins - every day

**Task**

https://practice.automationtesting.in/test-cases/
Under Shop
1,2,3,8,9,10
