### ISSUE TITLE
Automation Testing for 6 Scenarios [Swati]

### ISSUE THREAD

**Issue by Siyaa-Jhawar** [externship-sag/RSATeam1#113]
### **Criteria**

- [x] Create a new project
- [x] Use page object model
- [x] Create feature files for each scenario
- [x] After completing all 6 scenarios, try parallel execution
- [x] Create your own repository
- [x] Push your code on a daily basis
- [x] Execute your automation from Jenkins - every day

### **Task**
-------
https://practice.automationtesting.in/test-cases/
Under Shop
1,2,3,8,9,10
