### ISSUE TITLE
NPTEL, CoursEra & SimpliLearn short courses[Usha]

### ISSUE THREAD

**Issue by Usha-Sree-K** [externship-sag/RSATeam1#128]
**### Tasks for the current Sprint:**

- [ ] https://www.udemy.com/course/pmi-acp-certification-course/learn/lecture/19201238#overview

- [x] https://support.atlassian.com/jira-cloud-administration/docs/edit-an-issue-workflow/

- [x] https://lms.simplilearn.com/courses/2739/Agile-Scrum-Master%28ASM%C2%AE%29/syllabus
- [ ] 
- [ ] https://git-scm.com/book/en/v2/Getting-Started-What-is-Git%3F
-------------------------------------------------------------------------------------------------------

- [ ] https://www.coursera.org/learn/how-to-use-roadmaps-in-jira/home/week/1
- [ ] https://www.coursera.org/learn/agile-atlassian-jira/home/week/3
- [ ] https://www.coursera.org/learn/agile-atlassian-jira/lecture/IvFmP/visualizing-work-boards
- [ ] https://www.linkedin.com/learning/devops-foundations-lean-and-agile/what-is-agile
- [x] https://www.simplilearn.com/agile-and-scrum/pmi-acp-certification-training?tag=agile%20and%20lean#course-curriculum
- [ ] https://archive.nptel.ac.in/courses/110/104/110104073/
 **NPTEL Courses for _Software Project Management_  -     COORDINATED BY IIT, KHARAGPUR** 
   National Programme on Technology Enhanced Learning (NPTEL)

**Comment by Usha-Sree-K** [comment]
https://salesforce.wd1.myworkdayjobs.com/en-US/External_Career_Site?q=Return+to+Work&locations=63fde0f0bde8443991ca02ef79a929f8

**Comment by Usha-Sree-K** [comment]
Some tasks were incomplete. Started Pursuing Udemy Course on PMI - ACP(suggested my Mentor)
